### ISSUE TITLE
startup.sh should check for all launcher logs 

### ISSUE THREAD

**Issue by pyltime** [rstudio/rstudio-docker-products#102]
Feedback from a customer (in private ticket 58975):

> there's a script on the rstudio docker image at /usr/local/bin/startup.sh that tails a bunch of log files.  As of now, it pulls from /var/lib/rstudio-launcher/Local, in addition to other common logs.  It'd be useful if that script figured out how to pull in the log file of actual launcher profile in use (in my case this is Kubernetes).

**Comment by colearendt** [comment]
This is taken care of in the latest images
