### ISSUE TITLE
Create RSP and RSC images for Centos7

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/rstudio-docker-products#110]
Public sector organizations use centos7 / RHEL 7 as their default images. They'd like to rely on our docker images rather than building their own. Making docker images for this distro would be a big plus.

**Comment by colearendt** [comment]
Related to #111 

Thanks for the issue and the proposed PR! There are a couple of other things we will need to explore hardening before we formalize support for another operating system, but it's great to have this to track and the proposed implementation in your PR!

**Comment by colearendt** [comment]
#411  is related

Closing for now. We will keep evaluating additional operating systems in future discussions!
