### ISSUE TITLE
Improve init mechanism for RStudio Server Pro image

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio-docker-products#114]
We should evaluate supervisord (in use by https://github.com/rstudio/sol-eng-demo-server) and S6 (used by `rocker` and here: https://www.google.com/url?q=https://github.com/just-containers/s6-overlay&sa=D&source=editors&ust=1620667214417000&usg=AOvVaw2aD27QL-1VKAbNr9xWCDD1)

This should also be extensible for things like `sssd` / etc. (And we should consider adding `sssd` to the container anyways). Ideally with a way to stop services as well

**Comment by colearendt** [comment]
@caljnj I'm so sorry for the trouble you've had with this! Thank you for all of this information and the example to work with! I'm hoping we will get a chance to dig into improving the container setup here and address a bunch of your concerns. 

We still see this image mostly as a starting point / jumping off point, since the needs of our customers are very diverse and it is unlikely that we would ever be able to hit all needs with a single or even a handful of images. However, the point is well taken that hardening and improving the images, as well as documenting and sharing patterns in use, would be very valuable to our customer base!

Admittedly, this is one of the goals of the "R Admins" section on RStudio Community. The hope is that at some point there will be a community of administrators who feel comfortable sharing the different ways that they have tackled problems https://community.rstudio.com/c/r-admin/5

**Comment by caljnj** [comment]
Hi Cole. oops didnt realize you were an employee until now. haha. 

Great thanks! If possible would be great if you could log some of the discussion publicly here so i can follow along :)
very interested to see how you approach all of the elements. 

thanks for direction to the "R Admins". I added a post there to actually see how much interest there is for a reference-image for Active Directory setup.

**Comment by alessap** [comment]
@colearendt I hope this issue not too old. I wanted to give my two cents and I would definetely upvote adding the following dependency to rstudio-workbench and r-session-complete Docker images in order to enable kerberos authentication:

```bash
apt install krb5-user -y
```

This would avoid the need of customizing these images.

**Comment by colearendt** [comment]
@alessap Thanks for the note here! That is definitely a reasonable addition IMO 😄

**Comment by alessap** [comment]
@colearendt That is great to hear! I will fork the repo and create a PR then 😊
