### ISSUE TITLE
Add better image testing as a part of CI

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio-docker-products#115]
Right now image testing is limited (no licensing) and does not gate a `docker push`.  We should fix that! 

- [ ] Explore and attempt each of the items listed below in the comments
- [ ] For items that don't look possible now, explain why in a comment or create a follow-up ticket

**Comment by colearendt** [comment]
Some ideas for things to test:
- R and Python versions in all images (changing them should be considered a breaking change)
- Add licensing to the docker-compose files (from the parent environment, then provide env vars via Actions secrets)
- Start the products (or for RSP, run `verify-installation`) and ensure that they work
- Expected RStudio UID/GIDs exist and are unchanged (changing UID/GID in the container should be considered a breaking change)
- After startup, expected log files exist (or do not exist, in the case that we are properly echoing to stdout/stderr)

**Comment by bdeitte** [comment]
Thanks for all the thoughts!  I'm a little leery of the licensing parts unless it's only done on the main branch, and I can explain why in Slack to you.  In the original description I see "we should see if there is a way to simplify the CI pipeline away from docker Hub's hooks".  Is that still the case?  I don't remember seeing dockerhub hooks in how this was kicked off right now.

**Comment by colearendt** [comment]
Woops - sorry for the delay getting back to this. What makes you leery of licensing parts on just the main branch? That someone could do a PR from a fork and get the license? Actions never run on/from forks with secrets 😄 I don't know that GitHub has made this very clear, but I am glad they implemented it that way!

Also, that's right - some of the `hooks` directories are still hanging around, but they are not in use anymore
