### ISSUE TITLE
Unable to build rstudio connect docker image

### ISSUE THREAD

**Issue by devivaraprasad901** [rstudio/rstudio-docker-products#140]
Hi,

I am using docker destop to download rstudio connect and I can see below path successfully.
root@565ad3ca8b23:/opt/rstudio-connect/bin# ls
configdigest  connect  feature-usage  license-manager  migrate  rscadmin  usermanager

But when I am going to create my own dockerfile with your provided dockerfile. Where I am unable to see the path like above one. I can see only /opt/rstudio-connect-runtime only

**Comment by aronatkins** [comment]
It appears as if you are using the "connect-content-init" directory, which defines an init container and not a general-purpose RStudio Connect image.

Please use the "connect" directory as an example when building your own Dockerfile and Docker image.
<https://github.com/rstudio/rstudio-docker-products/tree/main/connect>

The "connect" directory is used to build the `rstudio/rstudio-connect` images, hosted on Docker Hub here: <https://hub.docker.com/repository/docker/rstudio/rstudio-connect>

**Comment by devivaraprasad901** [comment]
Hi Aronatkins,

Could you please help me to resolve the below error.

 => => exporting layers                                                                                                     15.1s
 => => writing image sha256:e4e6394a3eef053fa00f5eedc88192a822b05d90c17566b01f68084ecf4fefa1                                 0.0s 
 => => naming to docker.io/rstudio/rstudio-server-pro:1.4.1717-3                                                             0.0s 

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
WARNING: Image for service rstudio-server-pro was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building rstudio-connect
[+] Building 6.5s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                         0.1s 
 => => transferring dockerfile: 2.58kB                                                                                       0.0s 
 => [internal] load .dockerignore                                                                                            0.2s 
 => => transferring context: 2B                                                                                              0.0s 
 => ERROR [internal] load metadata for docker.io/rstudio/r-base:3.6.2-bionic                                                 6.0s 
------
 > [internal] load metadata for docker.io/rstudio/r-base:3.6.2-bionic:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/rstudio/r-base/blobs/sha256:c437c12769cd0f9d2b80a030b2184fcb11eb46d4969fc4f1441d505f30160514: 502 Bad Gateway
ERROR: Service 'rstudio-connect' failed to build : Build failed
PS C:\Users\Devivaraprasad_Varap\Documents\argomlops_iris\rstudio-docker-products-main>

**Comment by aronatkins** [comment]
Is that error repeatable?

The `502 Bad Gateway` HTTP error usually indicates that some gateway or proxy server is having trouble talking with some upstream server. In this case, it is probably either a service disruption with the Docker registry or a corporate proxy.

As of right now, the Docker status page is not showing indication of service problems: https://status.docker.com

Explanation of the HTTP 502 status code: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502

**Comment by aronatkins** [comment]
@devivaraprasad901 - please reach out to support@rstudio.com if you need additional assistance getting started with custom Docker images.
