### ISSUE TITLE
Build got successfull but rstudio connect application not getting started.

### ISSUE THREAD

**Issue by devivaraprasad901** [rstudio/rstudio-docker-products#143]
Hi All,

Please find the below error logs and how to rectify this Unable to launch a sandbox with Applications.RunAs as 'rstudio-connect'; may not be a real user or may not have sufficient permission in docker file. Could you please help us.

2021/06/21 16:51:03 Configuring licensing to use a local license...
2021/06/21 16:51:03 Unable to obtain a valid license: Your RStudio Connect license has expired. Please contact your Customer Success representative or email sales@rstudio.com to obtain a current license.
2021/06/21 16:51:03 Using the normalized Server.Address: http://localhost:3939/
2021/06/21 16:51:03 Error: Unable to launch a sandbox with Applications.RunAs as 'rstudio-connect'; may not be a real user or may not have sufficient permission: exit status 1; output: 21 Jun 2021 16:51:03 [rsandbox] ERROR system error 1 (Operation not permitted); OCCURRED AT int main(int, char* const*) src/cpp/server/sandbox/SandboxMain.cpp:158; LOGGED FROM: int main(int, char* const*) src/cpp/server/sandbox/SandboxMain.cpp:159
+ deactivate
+ echo 'Deactivating license ...'
+ /opt/rstudio-connect/bin/license-manager deactivate
Deactivating license ...

**Comment by colearendt** [comment]
Hello @devivaraprasad901 ! 

Thanks for reaching out here! Usually this happens because the `--privileged` flag has not been set for the docker container.

I.e.
```
# will throw error
docker run -it --rm -p 3939:3939 -e RSC_LICENSE rstudio/rstudio-connect:1.8.8.2

# will not throw error
docker run -it --rm --privileged -p 3939:3939 -e RSC_LICENSE rstudio/rstudio-connect:1.8.8.2
```

Do you mind sharing the `docker run` command or other mechanism you are using to launch the container?
