### ISSUE TITLE
Add functional-service testing for goss

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio-docker-products#155]
It would be nice to test that services actually run successfully / properly in goss. However, this is hard because goss tests are parallelized. 

We need to add licenses into secrets for GitHub Actions and make easy make targets / etc. for testing locally (i.e. `- RSC_LICENSE` in `docker-compose.test.yml` will use an env var that is defined in the user's environment variables without needing to put them in a `.env` file / etc.). You can look at how licenses are handled here if that's helpful: https://github.com/rstudio/sol-eng-docker#getting-started 

A couple of possible patterns:

1. Run the product inside of "timeout" so that we get an expected output if the product runs successfully for X seconds
https://github.com/rstudio/rstudio-docker-products/blob/de5f9c3cdbf03307d500f51225772f756c6e1aa9/connect/test/goss.yaml#L35
    - If we use this pattern, we should probably test / document the different behaviors
    - Downside: quite confusing setup, not using the startup script (in this example)

1. Run the product interactively:
    - i.e. https://github.com/nahara7/rstudio-docker-products/blob/08fd9e03e0456d2908ac213f37d1ab5979e06f32/package-manager/test/goss.yaml#L45
    - Downside: if the product is successful, then it will not return / the goss test will timeout
    - Also, we should look into why this is exiting 0 when "unhappy" (i.e. the product failed)
    - Downside: not using the startup script (in this example)

1. Run the product as a part of the testing script, and then check for listening in goss:
    - We could probably use `tini -- /usr/local/bin/startup.sh` consistently because that is the CMD/ENTRYPOINT for all of the product images. We will need to run into the background, maybe write to a log file, and then cat the log file if the tests exit unhappily? Getting logs is a secondary matter to testing that the product functions 😄 
    - could inject into https://github.com/rstudio/rstudio-docker-products/blob/main/server-pro/test/run_tests.sh
    - Downside: we are (potentially) more limited in what we can test in the goss.yaml because the service will already be running. This should be mostly academic / not a real downside though.

I lean towards option 3. What are your thoughts!?

A couple of notes:

- we will likely need to add the `privileged: true` flag to `docker-compose.test.yml`
- we will need to take a look at GitHub Secrets and see how they behave across forks, etc. @nahara7 if you'd like to work on this repo so that we can get "true" CI, then we can add your access and use a branch here rather than your fork!
- I would recommend testing some of these things interactively so you get a sense for what the goss tests are doing
    - i.e. start the container with `bash` i.e. `docker run -it --rm -e RSC_LICENSE --privileged rstudio/rstudio-connect:latest bash` 
    - then run the command `tini -- /usr/local/bin/startup.sh`, etc.
    
  

### Acceptance criteria:

- [ ] goss tests for rstudio-workbench check that the service runs properly
- [ ] goss tests for rstudio-workbench fail if there is misconfiguration of the product that prevents it from starting (i.e. add an invalid line like `hello=friend` to the `rserver.conf` file)
- [ ] goss tests for rstudio-connect check that the service runs properly
- [ ] goss tests for rstudio-connect fail if there is a misconfiguration of the product that prevents it from starting (i.e. add an invalid line like `Chicken=Little` to the config)
- [ ] goss tests for rstudio-package-manager check that the service runs properly
- [ ] goss tests for rstudio-package-manager fail if there is a misconfiguration of the product that prevents it from starting (i.e. add an invalid line like `Chicken=Little` to the config)

**Comment by nahara7** [comment]
I like number 3 as well ! After starting the product in `run_tests.sh` would you check for the process using a  goss test such as this? https://github.com/rstudio/rstudio-docker-products/blob/d9cf99b1f9b49b4a6b972573340d7395355a3c60/connect/test/goss.yaml#L49 ? And if it is not happy cat the log file ?

**Comment by colearendt** [comment]
Yeah! You can also use a "listen" rule to be sure it is listening where we expect - 3939 for Connect, etc.

As for "not happy / cat the log file," I think that's a nice to have that borders on unnecessary. I'm not sure where the right place to do that would be (goss won't give us that flexibility for a while, I don't think: https://github.com/aelsabbahy/goss/issues/483) - maybe in `run_tests.sh` if the `$?` exit code for the goss tests is unhappy?

**Comment by bdeitte** [comment]
Nahara needs to help with secrets to get this working- she is going to ask Cole his thoughts, and the rest of the team can help as needed (or learn)
