### ISSUE TITLE
Unable to  do EmailSetup with SMTP in rstudio connect

### ISSUE THREAD

**Issue by devivaraprasad901** [rstudio/rstudio-docker-products#163]
Hi All,

I have added Server and SMTP details in rstudio-connect.gcfg, while creating container License get deactivated due below yellow color highlighted errors.

Error details:

+ unset RSC_LICENSE
+ unset RSC_LICENSE_SERVER
+ /opt/rstudio-connect/bin/connect --config /etc/rstudio-connect/rstudio-connect.gcfg
2021/07/15 14:06:31 Resource limits: {"nofile":{"soft":1048576,"hard":1048576}}
2021/07/15 14:06:31 RStudio Connect running with PID 18
2021/07/15 14:06:31 Starting RStudio Connect v1.8.8.2
2021/07/15 14:06:31 Loaded server migration from '/etc/rstudio-connect/rstudio-connect-migration.gcfg'
2021/07/15 14:06:31 Error: Couldn't read configuration file '/etc/rstudio-connect/rstudio-connect.gcfg': warnings:
can't store data at section "SMTP", variable "DataDir"
can't store data at section "SMTP", variable "Address"
Deactivating license ...
+ deactivate
+ echo 'Deactivating license ...'
+ /opt/rstudio-connect/bin/license-manager deactivate

Email Setup and SMTP configuration added in rstudi connect config file and building the docker image: I have provided credentials and senderEmail in place of User, Password and Host.

[Server]
Address = https://rstudio-connect-pks.dell.com
EmailProvider = SMTP
SenderEmail = 
EmailSubjectPrefix = Rstudio
ViewerKiosk = false
HideEmailAddresses = false
MailAll = false

[SMTP]
Host = 
Port = 587
SSL = true
User = 
Password =

**Comment by colearendt** [comment]
Interesting - I thought I wrote up a response to this, but I must have lost it / it must have gotten misplaced.

A couple of things:

- This looks like an issue configuring RStudio Connect. I would recommend reaching out to our support team (support@rstudio.com) or your CS representative for these types of issues, as they are not related to the docker images themselves
- Another avenue for these types of informal discussions is the RStudio Community: https://community.rstudio.com/c/r-admin/rstudio-connect/27
- This error message suggests that your config file is longer than shown here, and says that the "DataDir" and "Address" fields cannot be put under the `[SMTP]` header. I suspect your whole file looks like the following:
```
[Server]
Address = https://myserver.com
EmailProvider = SMTP
SenderEmail =
EmailSubjectPrefix = Rstudio
ViewerKiosk = false
HideEmailAddresses = false
MailAll = false

[SMTP]
Host =
Port = 587
SSL = true
User =
Password =



 




DataDir = somevalue
Address = somevalue
```

If you remove those last two lines, things should work!
