### ISSUE TITLE
Support for Ubuntu Focal?

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio-docker-products#166]
The current `rsp-session` tarball originates from a [xenial](https://github.com/rstudio/docker-r-session-complete/blob/5d458fefb7ff0ec9865498e383c28a79aa0022f2/r-session-complete/bionic/Dockerfile#L30) base. 

Given that Xenial soon reaches its end of support and that the `libssl1.0` requirement blocks using `focal` as the `FROM:` layer (because `libssl1.0` cannot be installed on focal), I was wondering if there are plans to provide newer sources for the `rsp-session` tarball?

We've tried other Ubuntu refs than Xenial in the download URL but it seems no resources exist.

We are building our own images right now (for use in RSP + Kubernetes) from the Dockerfile of this repo (thanks for the initial work!).

cc @klrmlr

**Comment by kfeinauer** [comment]
We will be adding Focal images as part of #305.
