### ISSUE TITLE
See if there is a way to more easily reuse code across actions

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio-docker-products#184]
We have _lots_ of copy/paste in our github actions. Is it possible to build more generic actions that we can invoke in a more DRY fashion?

- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
- https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
- https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

Another useful doc:
- https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions

**Comment by kfeinauer** [comment]
This will be handled by #334.
