### ISSUE TITLE
r-session-complete jupyter symlink

### ISSUE THREAD

**Issue by samssann** [rstudio/rstudio-docker-products#197]
Could it be possible to add a symlink from /usr/local/bin/jupyter to /opt/python/PYTHON_VERSION/bin/jupyter so that the rstudio workbench default configurations work with the r-session-complate image without further configurations?

https://docs.rstudio.com/ide/server-pro/jupyter-sessions.html

**Comment by colearendt** [comment]
Closed by https://github.com/rstudio/rstudio-docker-products/pull/297
