### ISSUE TITLE
Add kinit to workbench and r-session image to allow for authentication with Active Directory (kerberos)

### ISSUE THREAD

**Issue by alessap** [rstudio/rstudio-docker-products#259]
User provisioning is possible using `sssd` owever there is a component missing for users who need to authenticate using Active Directory, i.e. `kinit`.

Adding `krb5-user` to the Docker images dependencies will allow for users to authenticate using Active Directory. This is fundamental for users interacting with e.g. MS SQL databases where authentication is controlled by Active Directory and AD groups. 

I have addressed this issue in PR #258 where I have added `krb5-user` to both workbench and bionic r-session-complete.

**Comment by alessap** [comment]
@colearendt As a followup to your comment (https://github.com/rstudio/rstudio-docker-products/issues/114#issuecomment-1014735476) I have created a PR #258. I am not sure if there is anything missing so I would very much appreciate some feedback if I have missed a step or few. Thanks.

**Comment by colearendt** [comment]
Closed in #258
