### ISSUE TITLE
RSW: Uncritical `ServerSessionProxy` error after startup

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio-docker-products#266]
This is not really an issue that affects usage but it bugs me from a dev perspective 😄 

I am seeing the following message shortly after the daemonized startup of RSW

```
2022-02-04T15:07:59.751104Z [rserver] ERROR system error 2 (No such file or directory); OCCURRED AT void rstudio::core::http::LocalStreamAsyncClient::handleConnect(const rstudio_boost::system::error_code&) src/cpp/server/ServerSessionProxy.cpp:124
```

It can be reproduced via

```
docker run --privileged -it rstudio/rstudio-workbench:2021.09.2-382.pro1--03769bb
```

While it seems not to cause problems, I've gotten multiple (worried) questions about this one from various people asking if this might cause problems. Hence, somehow suppressing it would be awesome!

**Comment by colearendt** [comment]
Thanks for reporting this @pat-s ! There are unfortunately lots of different places that this error message could be coming from, but we added some diagnostic information to the error message so that we can start to narrow down where it's coming from and then what it would take to fix it 😄

**Comment by colearendt** [comment]
I haven't seen this issue lately. Hopefully resolved! Please let us know if you are still seeing, thanks!
