### ISSUE TITLE
Returning multiple Python PATHs

### ISSUE THREAD

**Issue by jonlinca** [rstudio/rstudio-docker-products#311]
When using the RStudio Connect content script `examine-image.sh` to generate the runtime.yaml, we noticed that it was generating multiple Python PATHs when no R installation was specified.

```
runtimes.yaml

  -
    name: registry.com/rstudio-connect/connect-content:py3.8.13
    python:
      installations:
        -
          path: /usr/bin/python3.6
          version: 3.6.9
        -
          path: /opt/python/3.8.13/bin/python3.8
          version: 3.8.13
```

The [logic here](https://github.com/rstudio/rstudio-docker-products/blob/7937b16e6df981c9f253578ecdc303a07e312d6c/content/scripts/examine-image.sh#L162) seems to be related to the issue. I think it should reference `PYTHON_FOUND` versus `R_FOUND`.

**Comment by aronatkins** [comment]
Thanks for reporting this problem and identifying the mistake. It should be fixed, now.
