### ISSUE TITLE
Fix azure-ml clamav scanning

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio-docker-products#350]
The azure-ml image build is frequently failing to perform clamav scanning:

```
#35 [clamav 3/4] RUN touch /clamupdate.log &&     chown clamav:clamav /clamupdate.log &&     freshclam --log=/clamupdate.log
#35 0.093 ERROR: Problem with internal logger (UpdateLogFile = /clamupdate.log).
#35 0.094 ERROR: initialize: libfreshclam init failed.
#35 0.094 ERROR: Initialization error!
#35 0.095 ERROR: Can't open /clamupdate.log in append mode (check permissions!).
#35 ERROR: process "/bin/sh -c touch /clamupdate.log &&     chown clamav:clamav /clamupdate.log &&     freshclam --log=/clamupdate.log" did not complete successfully: exit code: 2
```

**Comment by ianpittwood** [comment]
As far as I can tell, this last happened on this build 9 days ago: https://github.com/rstudio/rstudio-docker-products/actions/runs/2734854690

The error itself has been noted as early as 2005 so it seems to be common occurrence. The problem for us is that it seems to happen randomly, making it the worst type of bug. The most [recent discussion](https://ubuntuforums.org/showthread.php?t=2436199) I found noted that the logs are by default written with the ownership `clamav:adm`. I'm currently attempting to modify the way we're logging freshclam and clamscan to be closer to the default methods. Unfortunately, I have not been able to replicate the bug locally though.

**Comment by bdeitte** [comment]
@colearendt any thoughts on this?

**Comment by bdeitte** [comment]
After further discussion, Ian mentioned that he has a PR to switch to build things in a subdir which should always have the right permissions.
