### ISSUE TITLE
Connect 2022.07.0 broke Azure SSO 

### ISSUE THREAD

**Issue by jdebbink** [rstudio/rstudio-docker-products#357]
Just upgraded connect from 2022.06.2 to 2022.07.0 and the Azure SSO integration broke with this error:
```
AADSTS750032: SAML protocol response cannot be sent via bindings other than HTTP POST. Requested binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
```

**Comment by aronatkins** [comment]
Would you mind opening a support ticket reporting this issue? We will gather details about your environment and then get the right folks involved.
https://docs.rstudio.com/support/#open-a-support-ticket

**Comment by colearendt** [comment]
Closing in hopes that this was addressed through other channels. Please let us know if you are still running into trouble!
