### ISSUE TITLE
Implement linting on Dockerfiles

### ISSUE THREAD

**Issue by ianpittwood** [rstudio/rstudio-docker-products#369]
It looks like `hadolint` has been previously used on Dockerfiles in the repository, but was never formally implemented as a quality gate for Pull Requests. I think it would be beneficial to implement a linter so we can more closely follow Docker's best practices around images. We could also consider implementing pre-commit and some other linters/formatters around our other file types (.sh, .yml, .py, etc.).

**Comment by AlexMapley** [comment]
[hadolint](https://github.com/hadolint/hadolint) is great 👍
