### ISSUE TITLE
Explore a more comprehensive base image

### ISSUE THREAD

**Issue by ianpittwood** [rstudio/rstudio-docker-products#391]
Our current base image, [`r-base`](https://github.com/rstudio/r-docker), only installs an R version on top of a specified OS. There are many more commonalities between each pro product image so we could create a more comprehensive base image to simplify our pro product images and allows for easier updating.

**Comment by colearendt** [comment]
For the record, I would propose us using our `content-base` or `content-pro` images as the base image. These are already in use, represent "R and python," and the Workbench team is already considering using them as the base for `r-session-complete`

**Comment by ianpittwood** [comment]
Thanks @colearendt, I'll look into leveraging those.
