### ISSUE TITLE
Refactor Justfile and Makefile to be more cohesive

### ISSUE THREAD

**Issue by ianpittwood** [rstudio/rstudio-docker-products#395]
Currently, the Justfile and Makefile definitions repeat some of each other's functions. Ideally, each file should have clearly defined ownership of individual targets/actions. `make` should also be the cornerstone tool for building and testing as it's a standard tool whereas `just` is not. Any actions that we want to be replicable by customers should be accessible from `make`.

Here's how I propose we split the primary actions between the two files:
| **Action**                  | **Make**                                   | **Just**                               |
|-----------------------------|--------------------------------------------|----------------------------------------|
| Update driver versions      | Calls just                                 | Updates driver versions using sed      |
| Update pro product versions | Calls just                                 | Updates pro product versions using sed |
| Build images                | Builds images using Docker Buildkit/buildx | Calls make                             |
| Test images                 | Runs tests using goss and docker-compose   | Calls make                             |
| Get version                 | Calls just                                 | Runs get version script                |
| Lint                        | Calls just                                 | Runs hadolint against an image         |

Long or complicated tagets, such as version updates, should also be extracted to individual shell script files.

**Comment by aronatkins** [comment]
Are there good reasons to keep both the `make` and `just` tooling? Given that you want to extract the "meaty" stuff into separate scripts, could you favor only `make`?

**Comment by ianpittwood** [comment]
I'm fine with that. Just was only recently added so I assumed we want to keep it around.

**Comment by aronatkins** [comment]
@colearendt added the `Justfile` to avoid some struggles getting the correct `sed` arguments passed to the `update-*-versions` targets (since different flags are needed on different OSes). He can confirm but the requirement is really that it needs to be easy for folks to run those targets (using the correct `sed` arguments) on macOS and Linux hosts.

**Comment by colearendt** [comment]
I will say that I have a personal preference for `just` over `make`, which is part of the reason for the switch. It also beats having 10ish separate scripts 😄 And was easier to get the quoting right on the `sed` arguments. I'm open to discussion around whether `just` or `make` is preferable long term. I can see how `make` could be easier / more prevalent in customer environments, but it also feels like `just` may be easier to copy / paste commands out of. (i.e. just using bash semantics)
