### ISSUE TITLE
Does the RStudio Workbench image allow multiple versions of R?

### ISSUE THREAD

**Issue by yashgt** [rstudio/rstudio-docker-products#407]
Workbench has a feature that allows the user to choose the version of R. Can that be added to the Workbench docker image?

**Comment by ianpittwood** [comment]
Hi @yashgt! As far as the installed versions go, we currently ship the Workbench image with two R versions: 3.6 and 4.1. Both of these can be configured with the Docker build args `R_VERSION` and `R_VERSION_ALT` if you need different versions in your own builds.

On the runtime side, I did just try to run Workbench locally though and saw that the version dropdown isn't appearing when starting new sessions. I'll investigate that and get back to you if that's the problem you're currently encountering.

**Comment by ianpittwood** [comment]
Nevermind, I had a problem with my own local build. Using our latest release, I was able to see both R versions in an IDE session as shown in [this doc](https://docs.rstudio.com/ide/server-pro/r_versions/using_multiple_versions_of_r.html#switching-between-versions). Let us know if there's anything else we can help with!

**Comment by colearendt** [comment]
This may be related to #439 . Please let us know if you have any more issues here!
