### ISSUE TITLE
Separate Dockerfiles for Workbench release, preview, and daily channels

### ISSUE THREAD

**Issue by dskard** [rstudio/rstudio-docker-products#408]
As new features are added to Workbench, sometimes the Docker images are required to be built in different way. Currently we use a single Dockerfile to build the images for the releases, preview, and daily channels. Occasionally, these channels can be out of sync, where the single Dockerfile no longer works.

We should consider using separate Dockerfiles to build the images so that as changes that only affect a single channel are needed, they can be applied to that channel's Dockerfile.

**Comment by colearendt** [comment]
The current way that we mitigate this issue is via a different branch (i.e. for #410 , we are using the `dev` branch). The downside here is that our `daily` line needs to use the `dev` images for now: 

https://hub.docker.com/r/rstudio/r-session-complete-preview/tags?page=1&name=dev-

**Comment by colearendt** [comment]
Closing for now! Our hope is that separate branches can mitigate this need
