### ISSUE TITLE
Fix Github CI warnings for use of deprecated features

### ISSUE THREAD

**Issue by ianpittwood** [rstudio/rstudio-docker-products#418]
We started getting the following warning recently:
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
According to the changelog page, the `save-state` and `set-output` commands as we currently use them will be deprecated on May 31st 2023.

[https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by kfeinauer** [comment]
@ianpittwood will investigate this further and size this issue. If it is fairly small, this can wait until next year before May 31st.
