### ISSUE TITLE
Content - examine-images.sh and python 3.6.9

### ISSUE THREAD

**Issue by jlin1encana** [rstudio/rstudio-docker-products#423]
I am creating images for the Kuberentes Connect installation approach, including some R-only images.

In review of the output that is coming out of `content\scripts\examine-image.sh` , I noticed that it was picking up Python 3.6.9 when there was no Python being installed. When I look closer at my pipeline, for an image that is solely installing R, I see this:

`Found Python at /usr/bin/python3 in PATH with canonical location /usr/bin/python3.6 and version 3.6.9.`

I believe python 3.6.9 is getting installed with this chunk in the [Dockerfile.bionic](https://github.com/rstudio/rstudio-docker-products/blob/main/content/base/Dockerfile.bionic#L30).

Assuming that Python 3.6.9 is coming over because of some sort of dependency, is there a better way to adjust the [examine-image.sh](https://github.com/rstudio/rstudio-docker-products/blob/main/content/scripts/examine-image.sh#L162) file to ignore the Python in a `/usr/bin/python3.6` folder?

**Comment by aronatkins** [comment]
The `build-image-yaml.sh` and `examine-image.sh` scripts emit YAML containing everything they discover within the target images. You can remove the Python entries if you do not want that version of Python to be used.

You're probably right that one of the system dependencies is pulling in a Python installation and adding it to the `PATH`.

Could you tell us more about your pipeline? Is there an opportunity to adjust the YAML before it is used?

**Comment by jlin1encana** [comment]
Thanks. Basically I have a base content pipeline that runs (updates OS libraries then installs database odbc drivers) before I customize it. Part of this Dockerfile-base has the below, which is what is triggering python to be installed:

```
Dockerfile-base

# Now, install the system requirements for R packages.
RUN export DEBIAN_FRONTEND=noninteractive && \
        apt-get update \
        && \
        apt-get install -y \
        default-jdk \
        gdal-bin \
        git \
        gsfonts \
        imagemagick \
        libcairo2-dev \
        libcurl4-openssl-dev \
        libfontconfig1-dev \
        libfreetype6-dev \
        libfribidi-dev \
        libgdal-dev \
        libgeos-dev \
        libgl1-mesa-dev \
        libglpk-dev \
        libglu1-mesa-dev \
        libgmp3-dev \
        libharfbuzz-dev \
        libicu-dev \
        libjpeg-dev \
        libmagick++-dev \
        libmysqlclient-dev \
        libpng-dev \
        libpq-dev \
        libproj-dev \
        libsodium-dev \
        libssh2-1-dev \
        libssl-dev \
        libtiff-dev \
        libudunits2-dev \
        libv8-dev \
        libicu-dev \
        libxml2-dev \
        make \
        perl \
        tcl \
        tk \
        tk-dev \
        tk-table \
        unixodbc-dev \
        zlib1g-dev \
        && \
        rm -rf /var/lib/apt/lists/*
```

I'm not sure what is the best/preferred way of doing it

1. Remove the part that scans the PATH variable from `examine-images.sh`
2. I see @ianpittwood had added a `--no-install-recommends` to this build during the [refactor](https://github.com/rstudio/rstudio-docker-products/pull/421/files#diff-0d02fc6f3f99508136af5417f7f3cd7d6d7ed3fb6de35fb3b2b762816563a5a5L34), which I just noticed. Does it make more sense to do that?

**Comment by aronatkins** [comment]
@jlin1encana - The change in https://github.com/rstudio/rstudio-docker-products/pull/426 lets you skip `PATH` discovery when building the YAML.

If you know exactly the interpreters and their versions you are adding into your image, you can also generate the YAML yourself using your own pipeline.

**Comment by aronatkins** [comment]
@ianpittwood & @colearendt  - could you explain why `--no-install-recommends` was added to the package installation targets? That argument is not included in the instructions suggested by Package Manager (the original source of that system dependency list).

**Comment by ianpittwood** [comment]
> You're probably right that one of the system dependencies is pulling in a Python installation and adding it to the `PATH`.

Yes this is the case. There might be a few packages that use some component of Python, but I know for sure that `libglib2` requires some Python 3 components and is required by `R` itself. Python 3.6 is the default version provided on `bionic` too which also leads us to believe this is some underlying dependency.

> @ianpittwood & @colearendt - could you explain why `--no-install-recommends` was added to the package installation targets? That argument is not included in the instructions suggested by Package Manager (the original source of that system dependency list).

This is a [Docker best practice suggested by Hadolint](https://github.com/hadolint/hadolint/wiki/DL3015). It's a simple and (usually) safe way to optimize images. [Canonical themselves actually started suggesting to do it](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) as well. If there's a recommended package that we *need*, I would lean towards installing it explicitly rather than implicitly through an `apt` recommendation.

Unfortunately I don't think that flag would help with the issue of Python 3 getting installed since it's a sub-dependency of R.

**Comment by aronatkins** [comment]
@ianpittwood Thanks for the background. Would you mind making sure that the Package Manager team has this feedback? These content images were built using the packages and commands suggested by their R package details. There is other tooling that takes those commands verbatim.

**Comment by jlin1encana** [comment]
This is great. Thank you @aronatkins!
