### ISSUE TITLE
Workbench - how to consume metric data from graphite exporter

### ISSUE THREAD

**Issue by EdwardJ1n** [rstudio/rstudio-docker-products#441]
Hi team, 

Hope you are doing good. 

May I ask how to consume metric data from graphite exporter for workbench? 

We have tried to add graphite metrics as data source of grafana, and it doen't seem to work. 

http://10.24.3.214:31521/metrics
~~~
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 9.38e-06
go_gc_duration_seconds{quantile="0.25"} 7.1352e-05
go_gc_duration_seconds{quantile="0.5"} 0.000105133
go_gc_duration_seconds{quantile="0.75"} 0.000145474
go_gc_duration_seconds{quantile="1"} 0.000318758
go_gc_duration_seconds_sum 0.029569928
go_gc_duration_seconds_count 271
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 12
# HELP go_info Information about the Go environment.
...
~~~

Add the above URL to HTTP => URL: http://10.24.3.214:31521/metrics. 
But, it return message "404 page not found" while testing. 
I've also tried to input http://10.24.3.214:31521 without any luck. 

The port of graphite exporter is forwarded to 31521: 
~~~
NAME                                           TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
rstudio-workbench                              NodePort   172.20.88.241    <none>        80:32465/TCP,9108:31521/TCP     10h
...
~~~

Browse the URL: http://10.24.3.214:31521/, and got the following output: 
~~~
Graphite Exporter

Accepting plaintext Graphite samples over TCP and UDP on :9109

[Metrics](http://10.24.3.214:31521/metrics)
~~~

IMHO we need to find a way to check the performance metrics, since RRD tool is not working in workbench pod. 

Thanks, 
Edward

**Comment by colearendt** [comment]
Howdy Edward! Thanks for your patience here! 

Metrics are exposed at port 9108 on the pod - I typically test by `exec`ing into a pod and running `curl -s localhost:9108/metrics`

We do set the "old style" annotations for metrics scraping:
https://github.com/rstudio/helm/blob/41d58fa1d8e955c448eab55a01564adcf6bb1c90/charts/rstudio-workbench/templates/deployment.yaml#L29-L31

And it is possible to enable our `serviceMonitor` with `serviceMonitor.enabled=true`

https://github.com/rstudio/helm/blob/41d58fa1d8e955c448eab55a01564adcf6bb1c90/charts/rstudio-workbench/values.yaml#L298-L300
https://github.com/rstudio/helm/blob/main/charts/rstudio-workbench/templates/service-monitor.yaml
