### ISSUE TITLE
Update existing images to use new base images

### ISSUE THREAD

**Issue by ianpittwood** [rstudio/rstudio-docker-products#447]
This is a follow-up to the changes implemented by #415. It added a series of base images and base images with pro drivers for Ubuntu 18.04, Ubuntu 22.04, and CentOS 7 and drafted new Dockerfile definitions for each product that use these new base images. When ready, each of these products should be swapped over to the new base image.

- [ ] Connect
  - [ ] Ubuntu 18.04
  - [ ] Ubuntu 22.04
- [ ] ~~Package Manager~~
  - [ ] ~~Ubuntu 18.04~~
  - [ ] ~~Ubuntu 22.04~~
- [x] r-session-complete
  - [x] Ubuntu 18.04
  - [x] Ubuntu 22.04
  - [x] CentOS 7
- [x] Workbench
  - [x] Ubuntu 18.04
  - [x] Ubuntu 22.04
- [x] Workbench for Azure ML
  - [x] Ubuntu 18.04
  - [x] Ubuntu 22.04

For each image, we need to ensure that it builds, passes existing tests, and functions as expected. The respective `NEWS.md` should also be updated for each product as updates are made.

**Comment by ianpittwood** [comment]
Package Manager will be excluded from this change since it's the only one that made sense to keep on `r-base` per #464. We can reevaluate this at a later time.

**Comment by bschwedler** [comment]
Working with SolEng & Aron A. on how to manage Quarto versions within the images.

**Comment by ianpittwood** [comment]
Marking as blocked. We'll look at merging this along with some other changes at the next Connect release.

**Comment by ianpittwood** [comment]
PR has been put back into review.

**Comment by ianpittwood** [comment]
Requires #568
