### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by boxswapper** [rstudio/rstudio-docker-products#460]
I have been attempting to launche r-session-complete:bionic with 2022.12.0 Posit Workbench.

I keep getting the following error when I build the image or just pull it directly from the repository (rstudio/r-session-complete:bionic).  I was able to launch previous versions of the launcher (2022.07.02) but not the current release version.  I get the following error.

`standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by colearendt** [comment]
Howdy @boxswapper ! Are you still hitting this issue? 

Are you trying to use these containers on a new / M1 Mac? Some searching for this error message suggests it is an error coming from docker and that it is complaining about a platform compatibility issue. As a user of an M1 Mac, I definitely still have issues running these containers locally.

It would be good to hear more about the type of computer you are trying to run this on and what your `run` command is that generates this error!
