### ISSUE TITLE
Add jammy `content` images

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio-docker-products#474]
For consistency with the rest of the repo, and because bionic is near EOL

We probably need to evaluate if/when/how to switch to this... before GA? after GA?

**Comment by colearendt** [comment]
@dbkegley @aronatkins I'm curious about y'all's thoughts on this 😄

**Comment by aronatkins** [comment]
+1 to adding images.

Unclear when the default should switch, as that is a forced architecture change. Probably should discuss with the team and @kellobri.

**Comment by kellobri** [comment]
We should probably add them ahead of the Bionic EOL date of April. It seems like it would be surprising to _not_ cut over and move off of Bionic as default in April, but it sounds like we haven't done a change like this before so we don't know what to anticipate? (Our platform support model is to keep offering support for another 6 months beyond EOL)

**Comment by aronatkins** [comment]
That's right. The target image name is recorded and, if it happens to no longer be available, Connect will cycle through "rebuild" activity as that content attempts to run.
