### ISSUE TITLE
Dependency error building workbench from Ubuntu 22.04

### ISSUE THREAD

**Issue by warrenson** [rstudio/rstudio-docker-products#485]
Running the workbench build gives a dependency resolution error when building using the Ubuntu 22.04 base image only. The build works fine with the default Ubuntu 18.04 image.

I've truncated the output from the build command here. A full log of the build output is attached at the end.
```
[$ just IMAGE_OS=ubuntu2204 workbench/build
+ BUILDX_ARGS=
+ [[ '' != '' ]]
+ [[ '' == '' ]]
+ raw_tag_array=($(just _make-default-tag ubuntu2204))
++ just _make-default-tag ubuntu2204
echo "rstudio-workbench:ubuntu2204-$(just -f ../Justfile _get-tag-safe-version 2022.12.0+353.pro20)"
+ tag_array=()
+ for tag in $raw_tag_array
+ tag_array+=("-t" $tag)
++ just -f ../Justfile _parse-os ubuntu2204
+ docker buildx --builder= build --load -t rstudio-workbench:ubuntu2204-2022.12.0-353.pro20 --build-arg RSW_VERSION=2022.12.0+353.pro20 --build-arg R_VERSION=3.6.2 --build-arg R_VERSION_ALT=4.1.0 --build-arg PYTHON_VERSION=3.9.5 --build-arg PYTHON_VERSIO
N_ALT=3.8.10 --build-arg RSW_DOWNLOAD_URL=https://download2.rstudio.org/server/bionic/amd64 --file=./Dockerfile.ubuntu2204 .
[+] Building 37.5s (6/16)

...

#0 36.54 The following packages have unmet dependencies:
#0 36.63  rstudio-server : Depends: libssl1.0.0 but it is not installable or
#0 36.63                            libssl1.0.2 but it is not installable or
#0 36.63                            libssl1.1 but it is not installable
#0 36.63 E: Unable to correct problems, you have held broken packages.

 ...

ERROR: failed to solve: executor failed running ...

error: Recipe `build` failed with exit code 1
```

I've forced the ubuntu keyserver to use port 80, which has worked (I am behind a fairly strict firewall). Other than that I'm using the code from the main branch. https://github.com/rstudio/rstudio-docker-products/compare/main...powerPlant:rstudio-docker-products:powerplant-dev

Here is the complete output from the build command: [build.log](https://github.com/rstudio/rstudio-docker-products/files/10895373/build.log)

**Comment by ianpittwood** [comment]
Hi, @warrenson. Thank you for pointing this out. I'm looking into a fix now.

**Comment by ianpittwood** [comment]
Fix has been merged to `main`.
