### ISSUE TITLE
Update primary/symlinked R version to 4.2.2 for the base images

### ISSUE THREAD

**Issue by tnederlof** [rstudio/rstudio-docker-products#488]
Currently, base images are being built using `R_VERSION` of 3.6.3 which is also the symlinked R version (causing it to be the default R version in Pro Products further upstream).

Since 3.6.3 is over three years old it would be more appropriate to use an`R_VERSION` of 4.2.2 instead in base images. 3.6.3 could be `R_VERSION_ALT` although we may want to consider a more modern version such as 4.1.3

Variables set in the CI here:
https://github.com/rstudio/rstudio-docker-products/blob/main/ci.Justfile

**Comment by bdeitte** [comment]
Thanks for bringing this up- we are talking about this internally and trying to determine the best way to do this.  There's some complications around making this change given it would be breaking.  We are trying to think through how this process would work, as it has been a bit complicated to do things like this in the past.   @ianpittwood and @colearendt are currently looking to figure this out.

**Comment by bdeitte** [comment]
We are updating the R and Python versions for Workbench in https://github.com/rstudio/rstudio-docker-products/pull/499/files#diff-2f86e223e36828144c47326360c4d6370d690bd460956a43650e0a05c7d6e363R203

**Comment by colearendt** [comment]
We updated R to 4.2.3
