### ISSUE TITLE
Consider including common baseline packages in GCP Cloud Workstations image

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio-docker-products#515]
The IDE depends on various R packages for some basic pieces of functionality. It would be an improvement to the user experience for Cloud Workstations if some of these baseline packages were already part of the image:

- `rmarkdown`
- `shiny`
- `tidyverse`
- `tidymodels`
- `odbc`

**Comment by ianpittwood** [comment]
I added the packages from `rstudioapi::getRStudioPackageDependencies()` into the image.
