### ISSUE TITLE
Launcher jobs callback address not configured properly in Workbench for GCW

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio-docker-products#516]
When knitting an RMarkdown document, the document knits, but this error shows in the main RStudio window:
![image](https://user-images.githubusercontent.com/10444878/230543860-acf7fabe-595c-42b7-93df-625e33732a2f.png)

**Comment by ianpittwood** [comment]
I actually didn't reproduce this by calling `knit`, but I did run into this navigating to the "Workbench Jobs" tab in RStudio. `launcher-sessions-callback-address` is currently set to `127.0.0.1:80`, which I thought is what we would be targeting to callback to Workbench. We may need to provide the FQDN of the instance. @blairj09 I'll dig through the metadata of the instance, but we should ask Google what all information will be available to us (including an IP and FQDN) for updating configs.

**Comment by ianpittwood** [comment]
Changed to callback address to `0.0.0.0:80` (where `rserver` is currently bound) and it seems the Local launcher cluster is now working!
