### ISSUE TITLE
Weekly build pipeline for GCP Cloud Workstations image

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio-docker-products#519]
Google updates their base image weekly on Friday. They'd like us to automatically rebuild and publish our image for Cloud Workstations every week as well so that users always get the latest version of the base image, which includes Google tools that are updated frequently.

**Comment by ianpittwood** [comment]
The pipeline is roughly implemented now. It should build every Monday morning at 8am UTC. Unfortunately, I'm having some issues with the Goss tests after the OS change so currently it just builds and pushes.

**Comment by ianpittwood** [comment]
Pipeline is operational as of this morning, but I'm going to hold off on closing the ticket until we see a successful scheduled run on Monday.

**Comment by ianpittwood** [comment]
Everything that's failing inconsistently in the pipeline should now be fixed, I feel good enough to close this one out.
