### ISSUE TITLE
Symlink Quarto for GCP Cloud Workstation image

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio-docker-products#520]
We need to symlink Quarto that is bundled w/ RStudio Pro and make it available to the other editors. Info at: https://docs.posit.co/resources/install-quarto/#add-symlink-quarto 

Colorado does this automatically at the image level so that VS Code and JupyterLab will have Quarto available by default at their respective terminals.

**Comment by ianpittwood** [comment]
I installed and linked Quarto 1.3.324 in the image.
