### ISSUE TITLE
Move Workbench for GCW release images to an appropriately named GCAR

### ISSUE THREAD

**Issue by ianpittwood** [rstudio/rstudio-docker-products#529]
Google has requested that we publish our Workbench for GCW images to Google Cloud Artifact Registry. We already do that, but the current registry has "cloud-testing" in the name. We should move the Artifact Registry a project more appropriately named for our final release/production images.

**Comment by ianpittwood** [comment]
I created a new project named `posit-images`. This is how I'm picturing the image URL change once we're set up with GCAR in `posit-images`:

* Old: `us-central1-docker.pkg.dev/gcp-workstations-testing/posit/workbench-for-gcw`
* New: `us-central1-docker.pkg.dev/posit-images/cloud-workstations/workbench`

**Comment by msarahan** [comment]
That proposed image URL looks good to me.

**Comment by ianpittwood** [comment]
@jthomasmock I just pushed images to `us-central1-docker.pkg.dev/posit-images/cloud-workstations/workbench` this morning so we can share that URL. Unfortunately it looks like the latest base image release broke our builds again so the images there will be using the previous base image version until I get it fixed.

**Comment by jthomasmock** [comment]
Thanks Ian!

**Comment by ianpittwood** [comment]
The pipeline is fixed to push to the new GCAR now as well.
