### ISSUE TITLE
R-Studio Server Pro container instance immideately stops running (exited 124)

### ISSUE THREAD

**Issue by AadDijksman** [rstudio/rstudio-docker-products#53]
Dear R-Studio/Github,

Using image rstudio/rstudio-server-pro on an Ubuntu 18.04 LTS virtual machine I can start a container instance without persistent storage Home and configurations: 
```
$ docker run --name rstudiopro --privileged -it -p 8787:8787 -p 5559:5559 -d rstudio/rstudio-server-pro:latest
```

I also can start a stable running container instance making the home directories persistent:

```
$ docker run --privileged -it -p 8787:8787 -v $PWD/data/rsp:/home -d rstudio/rstudio-server-pro:latest
```

But when I start an instance with persistent configuration:

```
$ docker run --privileged -it -p 8787:8787 -v $PWD/data/rsp:/home -v $PWD/server-pro/conf/:/etc/rstudio -d rstudio/rstudio-server-pro:latest
```

the container immideately stops running giving an exited code 124. This code is nowhere to be found or explained on the internet and I can not explain why this last command is giving this much trouble. Can someone help me out?

Thanks in advance for thinking along and reacting and kind regards,

Aad Dijksman (the Netherlands)

**Comment by colearendt** [comment]
Thanks for sharing this and reaching out! What directory are you running this command in? Did you make any changes to the `server-pro/conf` files? What is the stdout that you get when you run the command? If you do `docker logs containername` what do you get?

You can also try the above command without `-d` to see if you get any clearer logging.

**Comment by AadDijksman** [comment]
Cole Arendt, thanks for your reply, you got the how do you say that in proper English, the finger on the right spot. I did accidentally change the conf-path I found out after your reply and this was the issue.  Thanks alot and kind regards,

Aad Dijksman (The Netherlands)

**Comment by colearendt** [comment]
Very glad to hear! "Hit the nail on the head" is a pretty common phrase in English too 😄 (Much better than hitting the finger holding the nail!)

I'll close this issue for now, but please let us know if you run into any more issues!
