### ISSUE TITLE
Creating running container mounting persistent configuration directory not working ...

### ISSUE THREAD

**Issue by AadDijksman** [rstudio/rstudio-docker-products#56]
Dear people,

Using the RStudio-server-pro image I understand that creating the image several configuration files are put in the /etc/rstudio directory of the container. Starting a container via docker-compose-up -d with persistent user and configuration data the container crashes immideately due to missing configuration files in the persistent directory.
Inspecting the container I see:

        "HostConfig": {
            "Binds": [
                "/data/docker/docker-data/users:/home:rw",
                "/data/docker/docker-data/etc/rstudio:/etc/rstudio:rw"

Running a container instance without persistent configuration I find several config files in the /etc/rstudio directory within the container.

As I suppose, but correct me if I am wrong, should mounting the container config directory /etc/rstudio/ with a persistent location /data/docker/docker-data/etc/rstudio/ create a situation in which I can find those config files in the persistent directory also. Or am I wrong? And if I am wrong (which happes a lot), how can I get those configuration files into that persistent location without crashing containers?

Thanks in advance and kind regards,

Aad Dijksman (The Netherlands)

**Comment by colearendt** [comment]
Hey @AadDijksman ! Thanks for reporting your issues with persistent mounting again and apologies for the trouble! 

The way that volumes work in docker is that what you mount into the container (i.e. your local, persistent files) overwrite (are taken in preference to) anything else in that location in the container itself. As a result, the local directory you are mapping (`/data/docker/docker-data/etc/rstudio`) will be used in lieu of anything we have put into the container itself.

To get the configuration files into the persistent location, you can do one of:
- copy them from their source here: https://github.com/rstudio/rstudio-docker-products/tree/master/server-pro/conf
- use the `docker cp` command to copy the files out of a running container (i.e. `docker cp mycontainer:/etc/rstudio /data/docker/docker-data/etc/rstudio`)
- write your own configuration files in the directory that you care about: `/data/docker/docker-data/etc/rstudio`

For a generic resource on volumes, I have found this to be somewhat technical but quite useful:

https://docs.docker.com/storage/volumes/

I hope that helps!
