### ISSUE TITLE
Restrict JupyterLab and Jupyter versions Docker images

### ISSUE THREAD

**Issue by gsingh91** [rstudio/rstudio-docker-products#581]
We currently only support jupyter upto version [3.x](https://docs.posit.co/ide/server-pro/jupyter_sessions/configuration.html#jupyter-versions), but in Workbench [docker images](https://github.com/rstudio/rstudio-docker-products/blob/dev/workbench/Dockerfile.ubuntu2204#L73), we install the latest which is 4.0
We should either restrict the version of jupyter in the docker image or make a note that we are currently testing for the latest and their might be some regression issues if the customer ends up using the latest version.

**Comment by jthomasmock** [comment]
Jupyter v7 is also out now, so we should account for specific versions of JupyterLab (3.x) and Jupyter Notebook (v6.x) until we are sure we are ready to support the latest of each.

**Comment by tnederlof** [comment]
@jthomasmock customers are running into this issue using the Workbench images. It looks like this got merged into the docs, should the same explicit version be added to the Dockerfile here as well? https://github.com/rstudio/rstudio-pro/pull/5144

**Comment by jthomasmock** [comment]
I would like for us to do so, for sure!

**Comment by jthomasmock** [comment]
@colearendt is this something you could help with?

**Comment by jthomasmock** [comment]
Closed by: https://github.com/rstudio/rstudio-docker-products/pull/640
