### ISSUE TITLE
`rstudio-server` user group no longer exists in `rstudio/rstudio-workbench:jammy`

### ISSUE THREAD

**Issue by jmcarpenter2** [rstudio/rstudio-docker-products#589]
Hi there!

I noticed that our production builds have been failing recently because the `rstudio-server` user group no longer exists. We use this group within the `rstudio/rstudio-workbench:jammy` docker image to ensure permissions are appropriately set within the container for our customers.

Here is proof that it fails.
`docker run -e RSW_LICENSE=XXX rstudio/rstudio-workbench:jammy groups`
only returns the following now
`root`

Our builds have been failing since the latest release of the image 4 days ago, but I can't seem to find a git commit that would have contributed to this in the recent PRs on this repo. The culprit appears to be image tag [jammy-2023.06.1--5a83f02](https://hub.docker.com/layers/rstudio/rstudio-workbench/jammy-2023.06.1--5a83f02/images/sha256-0dc4310ff9301acdffe7784e51f6b8c36184eaaf493dea26a5c11505ce394a26?context=explore) for sha `0dc4310ff930`

Was this change intended? I couldn't find any information about it in the `NEWS.md` file either.
- If the change was intended, is there a suggested path for migration and user permission management?
- If the change was not intended, what is the expected lifecycle of a patch being released? 

Please let me know if I can provide any additional information to help debug.

Thank you so much for looking into this for us!
Jason

**Comment by jmcarpenter2** [comment]
If anyone else is having issues with the latest release of `jammy`, you can pin to the latest working version instead as a temporary workaround

instead of 
`FROM rstudio/rstudio-workbench:jammy`
use
`FROM rstudio/rstudio-workbench:jammy-2023.06.1--3dc5e2f`

**Comment by ianpittwood** [comment]
@jmcarpenter2 this issue should be fixed now on the `jammy` image built earlier today. Please reopen this issue if you're still having problems.

**Comment by jmcarpenter2** [comment]
Thanks so much @ianpittwood ! Will check out the latest version! Appreciate your support
