### ISSUE TITLE
unable to build workbench/Dockerfile.ubuntu2204 

### ISSUE THREAD

**Issue by adRn-s** [rstudio/rstudio-docker-products#613]
At this moment (commit [7935496](https://github.com/maxplanck-ie/rstudio-docker-products/commit/7935496f88ec01443d4c526e7b78f5e504a90b52)), I get an error building `workbench/Dockerfile.ubuntu2204` , the offending line is [this one](https://github.com/rstudio/rstudio-docker-products/blob/7935496f88ec01443d4c526e7b78f5e504a90b52/workbench/Dockerfile.ubuntu2204#L73)

The error says: `/opt/python/3.8.15/bin/python: No such file or directory`

My fix, was to change the variable `PYTHON_VERSION_JUPYTER` to `PYTHON_VERSION`

**Comment by bschwedler** [comment]
Thanks for reporting this!

It looks like the automation to update versions does not currently apply to `PYTHON_VERSION_JUPYTER`.  We'll do a one-off fix for now and address this when we update the automation.
