### ISSUE TITLE
Extract common `RUN` blocks to shared scripts

### ISSUE THREAD

**Issue by ianpittwood** [rstudio/rstudio-docker-products#616]
We have a lot of common `RUN` blocks that are copied from project to project for things like package installation and system configuration. We could create some shared bash scripts to cut down on these repeated blocks and possibly make debugging easier.

Some common `RUN` blocks:
* Updating and upgrading system packages.
* Installing a list of system packages.
* Installing an R version.
* Installing a list of R packages.
* Installing a Python version.
* Installing a list of Python packages.
* Installing and configuring the Jupyter installation on Workbench projects.
* Installing a Posit product (Workbench, Connect, or PPM).
* Installing a custom LM for a service-based product.
* Installing Quarto.
* Installing `tini`.
* Installing `wait-for-it.sh`.

**Comment by costrouc** [comment]
Elevating this issue to due needs from internal requirements.

**Comment by ianpittwood** [comment]
I've made significant progress on this ticket by borrowing scripts from rstudio/marketplaces. Marking as blocked for now though because our build workflow is too broken to make these updates a simple process.

https://github.com/rstudio/rstudio-docker-products/pull/716

Blocker: https://github.com/rstudio/rstudio-docker-products/issues/717
