### ISSUE TITLE
Install virtualenv and build in the Package Manager image for git-builders

### ISSUE THREAD

**Issue by tnederlof** [rstudio/rstudio-docker-products#695]
Using the package-manager image today, fails when trying to setup a Python git builder due to the absence of `build` and `virtualenv`. This is especially painful when using our helm charts with the public images.

We should install these in the image itself into whatever Python PPM will use by default to do the git building so it just works when they follow the quickstart instructions.

**Comment by shepherdjerred** [comment]
This is a known issue in Package Manager. See: https://github.com/rstudio/package-manager/issues/12544
