### ISSUE TITLE
library(tidyverse) calls "timedatectl" and users get an awful error

### ISSUE THREAD

**Issue by adRn-s** [rstudio/rstudio-docker-products#720]
```
> library("tidyverse")
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
── Attaching core tidyverse packages ─────────────────────────────── tidyverse 2.0.0 ──

[...]

Warning message:
In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
  ```
  
The call to "timedatectl" happens in other places, for example when clicking the "Render" of a document. I have already told users to ignore the message. But the question remains... why is timedatectl being called in so many places? Of course, containers don't have systemd as PID 1... I'm actually considering relacing /usr/bin/timedatectl inside the container with a wrapper that outputs a similar format and see if I can trick the packages (or IDE?) that call this command...

**Comment by colearendt** [comment]
Thanks so much for reporting this @adRn-s !! What an annoying error. I can definitely see how this would concern users. I will pass this along upstream and see what we can do to make this a bit better 😄

**Comment by gaborcsardi** [comment]
@adRn-s To see where this is coming from can you please run this in a new R session, and show us the output?
```r
options(warn = 2)
library(tidyverse)
# error happens here
traceback()
```

Thanks!

**Comment by adRn-s** [comment]
Sure. This is what I got,

```
> options(warn = 2)

> library(tidyverse)
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Error: package or namespace load failed for ‘tidyverse’:
 .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: NULL
  error: package or namespace load failed for ‘lubridate’:
 .onLoad failed in loadNamespace() for 'lubridate', details:
  call: system("timedatectl", intern = TRUE)
  error: (converted from warning) running command 'timedatectl' had status 1

> library(lubridate)
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Error: package or namespace load failed for ‘lubridate’:
 .onLoad failed in loadNamespace() for 'lubridate', details:
  call: system("timedatectl", intern = TRUE)
  error: (converted from warning) running command 'timedatectl' had status 1

> Sys.timezone()
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Error in system("timedatectl", intern = TRUE) : 
  (converted from warning) running command 'timedatectl' had status 1
```

:) I will next check customizing the Renviron.site with TZ env-var. Hopefully that solves the issue (following, https://github.com/tidyverse/lubridate/issues/957#issuecomment-789890230 ). Before opening this issue here, I did try to set TZ env-var because I read it somewhere else, but it failed because I set it on our Dockerfile, and it wasn't really inherited into the `rsession` processes of the users on workbench (I tested with `env`   in the built-in Terminal of the IDE). Anyway, let me come back to you soon.

Btw, I'm running the repon from commit  b11f202529fc6f88404c8790e765e10bdd1c59b5  (november 2023).

**Comment by gaborcsardi** [comment]
Can you please run the last line as well, after the error? I.e. 
```
traceback()
```
That's show us where the error is coming from. It is almost surely from base R, but still worth to include proof here.

**Comment by adRn-s** [comment]
Interestingly, Sys.timezone only fails after I loaded lubridate, and according to the traceback it's calling timedatectl. Else, without having lubridate, it returns UTC. Anyway, I will close the issue now. The issue is fixed after setting TZ at Renviron. Thanks!

**Comment by colearendt** [comment]
Thanks for reporting this @adRn-s ! Setting the `TZ` variable in #725 should hopefully mean that this error message will not be shown to hundreds of folks in the future 😄 Appreciate your help making things better every day 🎉

**Comment by adRn-s** [comment]
> Before opening this issue here, I did try to set TZ env-var because I read it somewhere else, but it failed because I set it on our Dockerfile, and it wasn't really inherited into the `rsession` processes of the users on workbench (I tested with `env` in the built-in Terminal of the IDE).

You're welcome. Btw, keep in mind that the fix on your PR won't work really. There's a reason why I decided on using `Renviron.site`... it's the only way I found to pass env-vars down to the users' `R` process/ console/ session.
