### ISSUE TITLE
Install R 4.4.0 on r-session images 

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio-docker-products#759]
We need to support R 4.4.0 for PWB  and need to install it on the r-session images

**Comment by lachlansimpson** [comment]
This is now a requirement for Bioconductor 3.19: https://www.bioconductor.org/install/

We have support tickets requesting this feature. Please see ZD ticket #105100

**Comment by ianpittwood** [comment]
r-session-complete is on R 4.4.0 as of 5/9 - https://github.com/rstudio/rstudio-docker-products/blob/bef6d3d9f4f6d5e7cedef04b8eda4a9787266dcd/docker-bake.hcl#L171
