### ISSUE TITLE
hkp://keyserver.ubuntu.com:80 no longer worked for us

### ISSUE THREAD

**Issue by murraj** [rstudio/rstudio-docker-products#800]
When attempting to build the "base" product image under rstudio-docker-products, the following line in Dockerfile.ubuntu2204 did not work for us today:

```
 RUN gpg --batch --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 \
    && gpg --batch --verify /tini.asc /tini \
    && chmod +x /tini \
    && ln -s /tini /usr/local/bin/tini
```

After googling, I changed it to hkps

```
RUN gpg --batch --keyserver hkps://keyserver.ubuntu.com --recv-keys 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 \
    && gpg --batch --verify /tini.asc /tini \
    && chmod +x /tini \
    && ln -s /tini /usr/local/bin/tini
```

I also had to update a server reference in install_r.sh before it would work.

Can you please confirm the dockerfile and install_r.sh for ubuntu2204 is out of date?  If it should have worked, any reason why we would be getting a connection timeout with the original code? It did work for us earlier this month.

Thanks.

**Comment by murraj** [comment]
Had to also remove the following line from the workbench Dockerfile for unbuntu. Seems like port 80 no longer accessible so the docker build was just stuck waiting for it to respond.

# Pre 7/25/23 packages
    && gpg --keyserver keyserver.ubuntu.com --recv-keys 3F32EE77E331692F \

**Comment by ianpittwood** [comment]
Hi @murraj. Could you provide the error you're receiving? I haven't noticed any issues in our automated builds related to the keyserver as of late.

**Comment by murraj** [comment]
You can go ahead and close this issue. It is possible that the issue is on our side and that we can no longer use HTTP (hkp) and have to use HTTPS instead (hkps)

Thank you.
