### ISSUE TITLE
Create ENV var to disable launcher

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio-docker-products#9]
https://github.com/rstudio/rstudio-docker-products/blob/a7ddff5991edcd247d0e85f3dc6c38e3ba265d78/server-pro/startup.sh#L37-L38

I think to make this container ideal, we should make launcher "optional." A few reasons for this:

- If you want to use legacy behavior without the launcher (i.e. project sharing, load balancing local sessions, etc.)
- If you want to run the launcher in a separate container from RSP. This pattern isn't common yet, but it is something we may want to think about as an option longer term 😄

**Comment by danielfrg** [comment]
Agree, I thought about but decided to leave that out for the first pass.
